image: node:16

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "running release_job for $TAG"
  release:
    tag_name: '$CI_COMMIT_MESSAGE'
    description: '$CI_COMMIT_MESSAGE'
    ref: '$CI_COMMIT_SHA'
  only:
    refs:
      - larzac-uat
      - larzac-prod
    variables:
      # Run only when commit message starts with "Release v"
      - $CI_COMMIT_MESSAGE =~ /^v.*/
    changes:
      - CHANGELOG.md
      - package.json

test:
  needs:
    - release
  before_script:
    - npm install --location=global jest
    - npm run install:app
  script:
    - npm run test:apos
  only:
    refs:
      - larzac-uat
      - larzac-prod

manual_test:
  rules:
    - when: manual
      allow_failure: true
  before_script:
    - npm install --location=global jest
    - npm run install:app
  script:
    - npm run test:apos

deploy_larzac_uat:
  needs:
    - test
  before_script:
    - apt-get update -y && apt-get -y install rsync
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_AWS" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "NODE_APP_INSTANCE=larzac" > .env
    - echo "MONGO_INITDB_ROOT_USERNAME=root" >> .env
    - echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD_LARZAC_UAT" >> .env
    - touch deployment/vino-terr-ssh-key.pem
    - echo "$SSH_PRIVATE_KEY_AWS" > deployment/vino-terr-ssh-key.pem
    - echo "mongoDB:" > apos/config/local.yml
    - 'echo "  dockerUri: mongodb://root:$MONGO_INITDB_ROOT_PASSWORD_LARZAC_UAT@vino-terr-mongo:27017/vino-terr-larzac?authSource=admin" >> apos/config/local.yml'
    - git clone https://github.com/punkave/stagecoach
    - npm run install:app
  script:
    - stagecoach/bin/sc-deploy larzac-uat
  only:
    - larzac-uat

deploy_larzac_prod:
  needs:
    - test
  before_script:
    - apt-get update -y && apt-get -y install rsync
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_AWS" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "NODE_APP_INSTANCE=larzac" > .env
    - echo "MONGO_INITDB_ROOT_USERNAME=root" >> .env
    - echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD_LARZAC_PROD" >> .env
    - touch deployment/vino-terr-ssh-key.pem
    - echo "$SSH_PRIVATE_KEY_AWS" > deployment/vino-terr-ssh-key.pem
    - echo "mongoDB:" > apos/config/local.yml
    - 'echo "  dockerUri: mongodb://root:$MONGO_INITDB_ROOT_PASSWORD_LARZAC_PROD@vino-terr-mongo:27017/vino-terr-larzac?authSource=admin" >> apos/config/local.yml'
    - git clone https://github.com/punkave/stagecoach
    - npm run install:app
  script:
    - stagecoach/bin/sc-deploy larzac-prod
  only:
    - larzac-prod
