image: node:16

stages:
  - build
#  - test

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

build:
  stage: build
  script:
    - npm run install:app --cache .npm --prefer-offline
    - npm install -g jest
    - npm run test:apos
    - npm run cy:run
  only:
    - ci-lightsail

#test:
#  stage: test
#  script:
#    - npm install -g jest
#    - npm run test:apos
#    - npm run cy:run
#  only:
#    - ci-lightsail
