image: node:16

stages:
  #  - release
  #  - test
  - deploy

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

#release:
#  stage: release
#  image: registry.gitlab.com/gitlab-org/release-cli:latest
#  script:
#    - echo "running release_job for $TAG"
#  release:
#    tag_name: 'v0.$CI_PIPELINE_IID'
#    description: 'v0.$CI_PIPELINE_IID'
#    ref: '$CI_COMMIT_SHA'
#  only:
#    refs:
#      - ci-lightsail
#      - larzac-uat
#    variables:
#      # Run only when commit message starts with "Release v"
#      - $CI_COMMIT_MESSAGE =~ /^Release v.*/
#    changes:
#      - CHANGELOG.md
#      - package.json

#test:
#  stage: test
#  #  needs: [ "release" ]
#  before_script:
#    - npm install --location=global jest
#    - npm run install:app --cache .npm --prefer-offline
#  script:
#    - npm run test:apos

deploy_uat:
  stage: deploy
  #  needs: [ "test" ]
  before_script:
    - apt-get update -y && apt-get -y install rsync
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_LARZAC_UAT" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "NODE_APP_INSTANCE=larzac" > .env
    - echo "MONGO_INITDB_ROOT_USERNAME=root" >> .env
    - echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD_LARZAC_UAT" >> .env
    - touch deployment/vino-terr-larzac-uat.pem
    - echo "$SSH_PRIVATE_KEY_LARZAC_UAT" > deployment/vino-terr-larzac-uat.pem
    - echo "mongoDB:" > apos/config/local.yml
    - 'echo "  dockerUri: mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@vino-terr-mongo:27017/vino-terr-larzac?authSource=admin" >> apos/config/local.yml'
    - git clone https://github.com/punkave/stagecoach
    - npm run install:app --cache .npm --prefer-offline
  script:
    - stagecoach/bin/sc-deploy larzac-uat
  only:
    - ci-lightsail
    - larzac-uat
