image: node:16

stages:
  - test

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

test:
  stage: test
  variables:
    JOB_NAME: test
    TARGET_BRANCH: main
  before_script:
    - apt-get update -y && apt-get -y install rsync
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_LARZAC_UAT" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "NODE_APP_INSTANCE=larzac" > .env
    - touch deployment/vino-terr-larzac-uat.pem
    - echo "$SSH_PRIVATE_KEY_LARZAC_UAT" > deployment/vino-terr-larzac-uat.pem
    - git clone https://github.com/punkave/stagecoach
  script:
    - npm run install:app --cache .npm --prefer-offline
    - npm install --location=global jest
    - npm run test:apos
    - stagecoach/bin/sc-deploy larzac-uat
  only:
    - ci-lightsail
    - larzac-uat
