image: node:16

stages:
  - test
#  - test

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

test:
  stage: test
  script:
    - npm run install:app --cache .npm --prefer-offline
    #    - npm install --location=global jest
    #    - npm run test:apos
    - git clone https://github.com/punkave/stagecoach
    - stagecoach/bin/sc-deploy uat
  only:
    - ci-lightsail

#test:
#  stage: test
#  script:
#    - npm install -g jest
#    - npm run test:apos
#    - npm run cy:run
#  only:
#    - ci-lightsail
