image: node:16

stages:
  - release
  - test
  - deploy

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "running release_job for $TAG"
  release:
    tag_name: 'v0.$CI_PIPELINE_IID'
    description: 'v0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'
  only:
    refs:
      - region-uat
      - region-prod
    variables:
      # Run only when commit message starts with "Release v."
      - $CI_COMMIT_MESSAGE =~ /^Release v.*/
    changes:
      - CHANGELOG.md
      - package.json

test:
  stage: test
  needs:
    - release
  before_script:
    - npm install --location=global jest
    - npm run install:app
  script:
    - npm run test:apos
  only:
    refs:
      - region-uat
      - region-prod

manual_test:
  stage: test
  rules:
    - when: manual
      allow_failure: true
  before_script:
    - npm install --location=global jest
    - npm run install:app
  script:
    - npm run test:apos

deploy_region_uat:
  stage: deploy
  needs:
    - test
  before_script:
    - apt-get update -y && apt-get -y install rsync
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_AWS" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "NODE_APP_INSTANCE=region" > .env
    - echo "MONGO_INITDB_ROOT_USERNAME=root" >> .env
    - echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD_region_UAT" >> .env
    - touch deployment/sample-project-ssh-key.pem
    - echo "$SSH_PRIVATE_KEY_AWS" > deployment/sample-project-ssh-key.pem
    - echo "mongoDB:" > apos/config/local.yml
    - 'echo "  dockerUri: mongodb://root:$MONGO_INITDB_ROOT_PASSWORD_region_UAT@sample-project-mongo:27017/sample-project-region?authSource=admin" >> apos/config/local.yml'
    - git clone https://github.com/punkave/stagecoach
    - npm run install:app
  script:
    - stagecoach/bin/sc-deploy region-uat
  only:
    - region-uat

deploy_region_prod:
  stage: deploy
  needs:
    - test
  before_script:
    - apt-get update -y && apt-get -y install rsync
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_AWS" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "NODE_APP_INSTANCE=region" > .env
    - echo "MONGO_INITDB_ROOT_USERNAME=root" >> .env
    - echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD_region_PROD" >> .env
    - touch deployment/sample-project-ssh-key.pem
    - echo "$SSH_PRIVATE_KEY_AWS" > deployment/sample-project-ssh-key.pem
    - echo "mongoDB:" > apos/config/local.yml
    - 'echo "  dockerUri: mongodb://root:$MONGO_INITDB_ROOT_PASSWORD_region_PROD@sample-project-mongo:27017/sample-project-region?authSource=admin" >> apos/config/local.yml'
    - git clone https://github.com/punkave/stagecoach
    - npm run install:app
  script:
    - stagecoach/bin/sc-deploy region-prod
  only:
    - region-prod
