placesAPI:
  name: Google Places
  url:
    prefix: https://maps.googleapis.com/maps/api/place
    search:
      url: nearbysearch/json
      querystring:
        radius: 10000
        limit: 10
    photo:
      url: photo

mongoDB:
  uri: mongodb://127.0.0.1:27017/vino-terr-larzac

register:
  minPasswordLength: 6

categories:
  - label: apostrophe:wineStore
    value: wineStore
    searchTerm: 'caviste'
  - label: apostrophe:wineBar
    value: wineBar
    searchTerm: 'bar à vins'
  - label: apostrophe:poi
    value: poi
    searchTerm: "lieu d'intérêt"

activities:
  - title: apostrophe:domainVisit
    image: map.svg
  - title: apostrophe:tasting
    image: glass.svg
  - title: apostrophe:directSale
    image: bottles.svg
  - title: apostrophe:organicWines
    image: organic.svg
  - title: apostrophe:bedAndBreakfast
    image: bed.svg

conveniences:
  - title: apostrophe:picnicArea
    image: picnic.svg
  - title: apostrophe:parking
    image: parking.svg
  - title: apostrophe:approvedPets
    image: pets.svg
  - title: apostrophe:restorations
    image: restoration.svg

wineLabels:
  - title: apostrophe:organicWines
    color: purple
  - title: apostrophe:biodynamics
    color: blue
  - title: apostrophe:organicAgriculture
    color: red
  - title: apostrophe:natureAndAdvance
    color: pink
  - title: apostrophe:terraVittis
    color: green

wineTypes:
  - title: apostrophe:red
  - title: apostrophe:rose
  - title: apostrophe:white
  - title: apostrophe:soft
  - title: apostrophe:effervesent
