placesAPI:
  name: Google Places
  url:
    prefix: https://maps.googleapis.com/maps/api/place
    search:
      url: nearbysearch/json
      querystring:
        radius: 10000
        limit: 10
    photo:
      url: photo

mongoDB:
  uri: mongodb://127.0.0.1:27017/vino-terr-larzac

register:
  minPasswordLength: 6

categories:
  - label: apostrophe:wineStore
    value: wineStore
    searchTerm: 'caviste'
  - label: apostrophe:wineBar
    value: wineBar
    searchTerm: 'bar à vins'
  - label: apostrophe:poi
    value: poi
    searchTerm: "lieu d'intérêt"
  - label: apostrophe:domain
    value: domain
    searchTerm: 'vignoble'

activities:
  - title: apostrophe:domainVisit
    image: map.svg
  - title: apostrophe:tasting
    image: glass.svg
  - title: apostrophe:directSale
    image: bottles.svg
  - title: apostrophe:organicWines
    image: organic.svg
  - title: apostrophe:bedAndBreakfast
    image: bed.svg
