placesAPI:
  name: Google Places
  url:
    prefix: https://maps.googleapis.com/maps/api/place
    search:
      url: nearbysearch/json
      querystring:
        radius: 10000
        limit: 10
        keyword: caviste
    photo:
      url: photo
