#!/bin/bash

mkdir -p ../../mongo/data/db
mkdir -p $HERE/mongo/data
ln -sfn $HERE/../../mongo/data/db $HERE/mongo/data

mkdir -p ../../uploads
cp -r $HERE/../../uploads $HERE/apos/public
echo "ApostropheCMS attachments restored"

PROJECT=vino-terr-larzac
DIR=/opt/stagecoach/apps/$PROJECT
DEPLOYMENTS=$DIR/deployments
KEEP=5
KEPT=$[$KEEP+1]
echo "Remove old deployments with sudo"
find "$DEPLOYMENTS" -mindepth 1 -maxdepth 1 | sort -r | tail -n +$KEPT | xargs sudo rm -rf

make prod
echo "Site started"
