#!/bin/bash

HERE=`pwd`

# save db
make db-dump
echo "DB saved"

sudo cp -r $HERE/apos/public/uploads/attachments $HERE/../../uploads
echo "ApostropheCMS attachments saved"

docker-compose stop
docker rm --force sample-project-mongo
docker rm --force sample-project-apos

echo "Site stopped"
